language: node_js
node_js:
  - "8"
  - "9"
  - "10"
env:
  matrix:
  - TEST_SUITE=lint
  - TEST_SUITE=build
  - TEST_SUITE=unit
  - TEST_SUITE=docs
matrix:
  exclude:
    - node_js: "8"
      env: TEST_SUITE=lint
    - node_js: "8"
      env: TEST_SUITE=docs
    - node_js: "9"
      env: TEST_SUITE=lint
    - node_js: "9"
      env: TEST_SUITE=docs
cache:
  directories:
  - node_modules
  - "$(npm config get prefix)/node_modules"
script:
- npm run test:$TEST_SUITE
after_success:
- ./coveralls_upload.sh
jobs:
  include:
  - stage: npm release
    node_js: '10'
    script: 
    - npm run build
    - git clone https://github.com/donmahallem/ngManniSpotter.git
    - cp ./release/environment.ts ./ngManniSpotter/src/environments/environment.ts
    - cp ./release/environment.ts ./ngManniSpotter/src/environments/environment.prod.ts
    - cd ./ngManniSpotter
    - npm install
    - ng build --aot --prod --base-href=./
    - cd ..
    - cp -r ./ngManniSpotter/dist/manniweb ./dist/app
    if: tag IS present
    deploy:
      provider: npm
      skip_cleanup: true
      email: $npm_email
      api_key: $npm_api_key
      on:
        tags: true
        repo: donmahallem/ManniSpotterDesktop
  - stage: Release Asar
    node_js: '10'
    script:
    - npm run build
    - git clone https://github.com/donmahallem/ngManniSpotter.git
    - cp ./release/environment.ts ./ngManniSpotter/src/environments/environment.ts
    - cp ./release/environment.ts ./ngManniSpotter/src/environments/environment.prod.ts
    - cd ./ngManniSpotter
    - npm install
    - ng build --aot --prod --base-href=./
    - cd ..
    - cp -r ./ngManniSpotter/dist/manniweb ./dist/app
    - npm run build:asar
    #if: tag IS present
    deploy:
      provider: releases
      skip_cleanup: true
      api_key: $GITHUB_TOKEN
      file: ./release/app.asar
      on:
        tags: true